# Pizza Order Management System - Development Docker Compose
# This file extends the main docker-compose.yml for development with volume mounting

version: '3.8'

services:
  # Backend API Service - Development
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: pizza-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      HOST: 0.0.0.0
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: pizza_orders
      DB_USER: pizza_user
      DB_PASSWORD: pizza_password
      DB_URL: postgresql://pizza_user:pizza_password@database:5432/pizza_orders
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_PREFIX: /api
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: debug
      JWT_SECRET: your-super-secret-jwt-key-here
      POLLING_ORDER_LIST_INTERVAL: 5000
      POLLING_ORDER_STATUS_INTERVAL: 3000
      WEBSOCKET_ENABLED: true
      UI_DEFAULT_ORDERS_PER_PAGE: 2
      UI_MAX_ORDERS_PER_PAGE: 4
    ports:
      - "3001:3001"
      - "9229:9229"  # Debug port
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pizza-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend React Service - Development
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: pizza-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      REACT_APP_API_BASE_URL: http://localhost:3001/api
      REACT_APP_WS_URL: ws://localhost:3001
      REACT_APP_UI_DEFAULT_ORDERS_PER_PAGE: 2
      REACT_APP_UI_MAX_ORDERS_PER_PAGE: 4
      REACT_APP_UI_MIN_ORDERS_PER_PAGE: 1
      REACT_APP_UI_DEFAULT_SORT_BY: orderTime
      REACT_APP_UI_DEFAULT_SORT_ORDER: desc
      REACT_APP_UI_AUTO_REFRESH: true
      REACT_APP_UI_REFRESH_INTERVAL: 5000
      REACT_APP_UI_MAP_DEFAULT_ZOOM: 12
      REACT_APP_UI_MAP_DEFAULT_LAT: 40.7128
      REACT_APP_UI_MAP_DEFAULT_LNG: -74.0060
      REACT_APP_FEATURE_REALTIME: true
      REACT_APP_FEATURE_MAP: true
      REACT_APP_FEATURE_RTL: true
      REACT_APP_FEATURE_DARK_MODE: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - pizza-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s