# Pizza Order Management System - Production Docker Compose
# This file defines the production setup with optimized configurations

version: '3.8'

services:
  # PostgreSQL Database Service (Production)
  database:
    image: postgres:15-alpine
    container_name: pizza-database-prod
    restart: always
    environment:
      POSTGRES_DB: pizza_orders
      POSTGRES_USER: pizza_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./server/src/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./server/src/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - pizza-prod-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pizza_user -d pizza_orders"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Redis Cache Service (Production)
  redis:
    image: redis:7-alpine
    container_name: pizza-redis-prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_prod_data:/data
    networks:
      - pizza-prod-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # Backend API Service (Production)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: pizza-backend-prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3001
      HOST: 0.0.0.0
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: pizza_orders
      DB_USER: pizza_user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: postgresql://pizza_user:${DB_PASSWORD}@database:5432/pizza_orders
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_PREFIX: /api
      CORS_ORIGIN: ${CORS_ORIGIN}
      LOG_LEVEL: info
      LOG_FORMAT: combined
      JWT_SECRET: ${JWT_SECRET}
      POLLING_ORDER_LIST_INTERVAL: 5000
      POLLING_ORDER_STATUS_INTERVAL: 3000
      WEBSOCKET_ENABLED: true
      UI_DEFAULT_ORDERS_PER_PAGE: 2
      UI_MAX_ORDERS_PER_PAGE: 4
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pizza-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Frontend React Service (Production)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: pizza-frontend-prod
    restart: always
    environment:
      NODE_ENV: production
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_WS_URL: ${REACT_APP_WS_URL}
      REACT_APP_UI_DEFAULT_ORDERS_PER_PAGE: 2
      REACT_APP_UI_MAX_ORDERS_PER_PAGE: 4
      REACT_APP_UI_MIN_ORDERS_PER_PAGE: 1
      REACT_APP_UI_DEFAULT_SORT_BY: orderTime
      REACT_APP_UI_DEFAULT_SORT_ORDER: desc
      REACT_APP_UI_AUTO_REFRESH: true
      REACT_APP_UI_REFRESH_INTERVAL: 5000
      REACT_APP_UI_MAP_DEFAULT_ZOOM: 12
      REACT_APP_UI_MAP_DEFAULT_LAT: 40.7128
      REACT_APP_UI_MAP_DEFAULT_LNG: -74.0060
      REACT_APP_FEATURE_REALTIME: true
      REACT_APP_FEATURE_MAP: true
      REACT_APP_FEATURE_RTL: true
      REACT_APP_FEATURE_DARK_MODE: true
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - pizza-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: pizza-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - pizza-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'

# Named Volumes (Production)
volumes:
  postgres_prod_data:
    driver: local
  redis_prod_data:
    driver: local

# Networks (Production)
networks:
  pizza-prod-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
